<?php
require_once 'db.php';

$trainers = array(
    array("id"=>"1","name"=>"Karolis Brusokas","specialization"=>"","description"=>"","education"=>"Aukštasis","location"=>"Šeškinės pradinė mokykla","phone"=>"+37062082727","email"=>"karolis@skm.lt","motto"=>"Elkis su kitais taip kaip norėtum, kad elgtusi su tavimi","achievements"=>"","image_url"=>"","image_visible"=>1,"order_index"=>0,"created_at"=>"2025-11-24 14:47:18"),
    array("id"=>"2","name"=>"Rolandas Mocevičius","specialization"=>"","description"=>"","education"=>"Aukštasis","location"=>"Kunigaikščio gedimino progimnazija ir Vilniaus Privati Gimnazija","phone"=>"+37067483461","email"=>"Rmocevicius@gmail.com","motto"=>"Elkis su kitais taip, kaip norėtum jog su tavimi elgtųsi","achievements"=>"","image_url"=>"","image_visible"=>1,"order_index"=>0,"created_at"=>"2025-10-22 11:01:44"),
    array("id"=>"3","name"=>"Goda Papartytė","specialization"=>"","description"=>"","education"=>"Vidurinis. 3 kurso studentė Vilniaus kolegijoje","location"=>"Gabijos progimnazija","phone"=>"+37062454412","email"=>"papartytegoda@gmail.com","motto"=>"enjoy the butterflies, enjoy being naive, enjoy the nerves, the pressure - no regrets, only memories.","achievements"=>"","image_url"=>"","image_visible"=>1,"order_index"=>0,"created_at"=>"2025-10-22 11:07:31"),
    array("id"=>"4","name"=>"Erika Filipavičiūtė","specialization"=>"","description"=>"","education"=>"Vidurinysis. Šiuo metu paskutinis (3kursas) kineziterapijos","location"=>"Vyturio pradinė mokykla","phone"=>"+37060223575","email"=>"erikutefil@gmail.com","motto"=>"Net mažiausia pastanga veda link didelių rezultatų","achievements"=>"","image_url"=>"","image_visible"=>1,"order_index"=>0,"created_at"=>"2025-10-22 11:20:10"),
    array("id"=>"5","name"=>"Melita Ribikauskaitė","specialization"=>"","description"=>"","education"=>"Vidurinis išsilavinimas. Šiuo metu antro kurso kineziterapijos studentė","location"=>"Maironio progimnazija","phone"=>"+37062669962","email"=>"melitaribikauskaite@gmail.com","motto"=>"Nėra ribų - yra tik tikslai","achievements"=>"","image_url"=>"","image_visible"=>1,"order_index"=>0,"created_at"=>"2025-10-22 12:26:49"),
    array("id"=>"6","name"=>"Arūnė Anskaitienė","specialization"=>"","description"=>"","education"=>"Kūno kultūros bakalauras, sporto vadybos magistras","location"=>"Prano Mašioto pradinė mokykla","phone"=>"+37060079372","email"=>"Arunebud10@gmail.com","motto"=>"-","achievements"=>"2024 m. Lietuvos fizinio ugdymo pedagogų apdovanojimas","image_url"=>"","image_visible"=>1,"order_index"=>0,"created_at"=>"2025-10-22 12:48:57"),
    array("id"=>"7","name"=>"Ugnė Skipariūtė","specialization"=>"","description"=>"","education"=>"VU Kineziterapijos 4 kurso studentė","location"=>"Jono Basanavičiaus progimnazija","phone"=>"+37067123388","email"=>"ugneskipa@gmail.com","motto"=>"Kiekviena diena - nauja galimybė tapti geresniu nei buvai vakar.","achievements"=>"","image_url"=>"","image_visible"=>1,"order_index"=>0,"created_at"=>"2025-10-22 22:43:08"),
    array("id"=>"8","name"=>"Elvita Vilkavickaitė","specialization"=>"","description"=>"","education"=>"Kineziterapija II kursas","location"=>"Vilniaus Prano Mašioto pradinė mokykla","phone"=>"+37062509935","email"=>"elvita.vilkavickaite@gmail.com","motto"=>"Maži žingsniai veda į didelius stebuklus","achievements"=>"","image_url"=>"","image_visible"=>1,"order_index"=>0,"created_at"=>"2025-10-23 09:34:17"),
    array("id"=>"9","name"=>"Vėjūnė Malūnavičiūtė","specialization"=>"","description"=>"","education"=>"Kineziterapijos II kursas, Vilniaus Kolegija","location"=>"J. Basanavičiaus progimnazija, Vyturio pradinė mokykla","phone"=>"+37065989149","email"=>"vejunemal@gmail.com","motto"=>"Sveikas kūnas - laimingo žmogaus namai","achievements"=>"","image_url"=>"","image_visible"=>1,"order_index"=>0,"created_at"=>"2025-10-23 12:10:24"),
    array("id"=>"10","name"=>"Domas Krivelis","specialization"=>"","description"=>"","education"=>"Tolesnis profesinis mokymas: Sveikatos priežiūros - gydomojo masažo specialistas (įgyta kvalifikacija). Priedui to: Aukštasis neuniversitetinis išsilavinimas: Kineziterapijos studijų programos paskutinio kurso studentas (kolegija).","location"=>"Vilniaus Jeruzalės progimnazija","phone"=>"062028068","email"=>"domas.krivelis@sportogalia.lt","motto"=>"Turime įsivaizduoti Sizifą laimingą.","achievements"=>"Multidisciplininis sportinis pasirengimas: karate, plaukimas, bėgimas, graikų-romėnų imtynės, futbolas, gatvės gimnastika, MMA (mišrieji kovos menai).","image_url"=>"","image_visible"=>1,"order_index"=>0,"created_at"=>"2025-11-03 12:15:05"),
    array("id"=>"11","name"=>"Benas Jonkus","specialization"=>"","description"=>"","education"=>"Kineziterapijos bakalauras","location"=>"Fabijoniškių gimn","phone"=>"+37066233130","email"=>"benasjonkus@gmail.com","motto"=>"Disciplina šiandien, laisvė rytoj","achievements"=>"Esu laimingas darydamas, tai ką darau, o tai be vargo ryte padeda išlipti iš lovos","image_url"=>"","image_visible"=>1,"order_index"=>0,"created_at"=>"2025-11-24 20:44:18"),
    array("id"=>"12","name"=>"Aurimas Maščinskas","specialization"=>"","description"=>"","education"=>"3 kurso kineziterapijos studentas","location"=>"Antakalnio gimnazija","phone"=>"060104529","email"=>"Aurisbasket@gmail.com","motto"=>"Klysk, Daryk, Atverk širdį, tobulėk","achievements"=>"3 kartus MKL čempionas, EYBL vicečempionas, RKL B vicečempionas, SKM fizinio rengimo treneris.","image_url"=>"","image_visible"=>1,"order_index"=>0,"created_at"=>"2025-11-26 15:09:39"),
    array("id"=>"13","name"=>"Viltė Lauciūtė","specialization"=>"","description"=>"","education"=>"Kineziterapeutė","location"=>"Pažinimo medis (Kalinausko g. 13)","phone"=>"+37061837395","email"=>"vilte.lauciute@gmail.com","motto"=>"Svarbu ne tai, kur nueisi, o kaip eisi ir ar galėsi mylėti tai, ką darai pakeliui","achievements"=>"Buvau profesionali balerina Lietuvos nacionaliniame operos ir baleto teatre, vėliau pasukau kineziterapijos keliu. Baigiau kineziterapijos bakalauro studijas Vilniaus kolegijoje, Šiuo metu studijuoju Fizinio ugdymo ir sporto magistrą Vytauto Didžiojo universitete. Domiuosi ir nuolat gilinu žinias šiose srityse.","image_url"=>"","image_visible"=>1,"order_index"=>0,"created_at"=>"2025-12-21 16:28:35"),
    array("id"=>"14","name"=>"Elina Cybulskaja","specialization"=>"","description"=>"","education"=>"Kineziterapijos studentė","location"=>"Vitlio darželis","phone"=>"+37060729051","email"=>"elina.15432@gmail.com","motto"=>"Judėk šiandien, kad galėtum gyventi rytoj","achievements"=>"Didžiuojuosi tuo, kad aktyviai šoku ir sportuoju, nuolat stiprindama savo kūną, ištvermę ir discipliną.","image_url"=>"","image_visible"=>1,"order_index"=>0,"created_at"=>"2026-01-06 12:07:02"),
    array("id"=>"15","name"=>"Aistė Dargevičiūtė","specialization"=>"","description"=>"","education"=>"LSU bakalauras, VIKO kineziterapijos studijos","location"=>"","phone"=>"+37064440585","email"=>"dargeviciute.aiste@gmail.com","motto"=>"Jei nori turėti tai, ko neturi, padaryk tai, ko dar niekad nesi daręs.","achievements"=>"","image_url"=>"","image_visible"=>1,"order_index"=>0,"created_at"=>"2026-03-15 18:28:51"),
    array("id"=>"16","name"=>"Hubertas Žičius","specialization"=>"","description"=>"","education"=>"Vilniaus kolegija. Reabilitacija- Kineziterapija II kursas","location"=>"Šiuo metu: Pažinimo medis (Ozo g. 37), Erudito Licėjus.","phone"=>"+37064190443","email"=>"hzicius@gmail.com","motto"=>"Pastovus noras tobulėti veda į nuostabius pokyčius gyvenime.","achievements"=>"Charakterio, asmenybės, lyderystės ir kitų savybių išsiugdymas savyje.","image_url"=>"","image_visible"=>1,"order_index"=>0,"created_at"=>"2026-03-15 18:58:17"),
    array("id"=>"17","name"=>"Kamilė Butavičiūtė","specialization"=>"","description"=>"","education"=>"II kurso kineziterapeutė","location"=>"Gedimino miesto mokykla, Erudito licėjus","phone"=>"+37068164696","email"=>"Butaviciutek@gmail.com","motto"=>"Viskas keičiasi, kai pradedi keistis pats. Jei ne dabar, tai kada","achievements"=>"6 metus žaidžiau krepšinį, tai buvo meilės pradžia sportui. O dabar sporto salė mano antri namai ir sporto pasiekimai dar ateityje.","image_url"=>"","image_visible"=>1,"order_index"=>0,"created_at"=>"2026-03-15 19:22:44"),
    array("id"=>"18","name"=>"Urtė Dieninytė","specialization"=>"","description"=>"","education"=>"Kineziterapijos bakalauras Vilniaus universitete (vis dar mokausi/ 3 kursas iš 4)","location"=>"Karalienės Mortos mokykla (Vilnius)","phone"=>"+37062352354","email"=>"urtedien@gmail.com","motto"=>"growth starts where comfort ends (Augimas prasideda ten, kur baigiasi komfortas)","achievements"=>"","image_url"=>"","image_visible"=>1,"order_index"=>0,"created_at"=>"2026-03-19 09:19:01")
);

writeData('trainers', $trainers);
echo "SUCCESS: " . count($trainers) . " treneriai irasyti!";
?>
